# -*- coding: utf-8 -*-
"""Assignment3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148bdHgazEq-08kb3Rfte3517y1ge9Hy2
"""

import numpy as np
import pandas as pd

def pearson_correlation(x, y):
    """
    Calculate Pearson correlation coefficient between two variables

    Args:
        x (array-like): First variable
        y (array-like): Second variable

    Returns:
        float: Pearson correlation coefficient
    """
    # Convert inputs to numpy arrays
    x = np.array(x)
    y = np.array(y)

    # Calculate means
    x_mean = np.mean(x)
    y_mean = np.mean(y)

    # Calculate numerator (covariance)
    numerator = np.sum((x - x_mean) * (y - y_mean))

    # Calculate denominator (product of standard deviations)
    denominator = np.sqrt(np.sum((x - x_mean)**2) * np.sum((y - y_mean)**2))

    # Calculate correlation coefficient
    r = numerator / denominator

    return r

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/sample_data/StudentsPerformanceLabeled-3.csv')

# Calculate correlation between reading and writing scores
reading_scores = df['reading_score']
writing_scores = df['writing_score']

correlation = pearson_correlation(reading_scores, writing_scores)
print(f"\nPearson correlation coefficient between reading and writing scores: {correlation:.4f}")

# Verify with pandas built-in correlation method
pandas_corr = df['reading_score'].corr(df['writing_score'])
print(f"Verification using pandas correlation: {pandas_corr:.4f}")

